### ISSUE TITLE
Invoke rocksdb destroy

### ISSUE THREAD

**Issue by cisaacson** [Level/rocksdb#67]
I am trying to invoke rocksdb destroy, using the level-rocksdb package. I cannot see how to get to the leveldown API to do this. I tried `db.db` after creating a database but it says no such method.

In a related question, the database has a status of 'opening' after I open it, is there a way to wait for it to open? I know the first usage usually does this, but what if I want to close it right away (or in this case test destroy).

Perhaps because the database is not yet open the leveldown API is not exposed? If so it would be good to know how to await (Typescript style) for it to open in every case.

**Comment by vweevers** [comment]
If the `db` is not yet open, `db.db` points to `deferred-leveldown`. It's not relevant to your `destroy` question though, because `destroy` is a static method (without a Promise API atm). Usage is:

```js
const level = require('level-rocksdb')

level.destroy('./db', function (err) {

})
```

As for your second question, explicit open looks like this:

```js
const level = require('level-rocksdb')
const db = level('./db')

await db.open()
```

This is JS, I assume `async/await` is similar in TS.

**Comment by cisaacson** [comment]
Thanks for the quick response, perfect.
